@Library('jenkins-upstream-library') _
def failedStages = []
pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:3256.v88a_f6e922152-2-jdk17.1'
            args '-v /etc/resolv.conf:/etc/resolv.conf -v /run/containerd/containerd.sock:/run/containerd/containerd.sock'
            label 'jump-vpc-x86_64'
        }
    }
    parameters {
        string(defaultValue: '', description: 'Build(quay image or build number)', name: 'Build')
        string(defaultValue: '30', description: 'Enter time(in Minutes) to retain the cluster', name: 'KeepFor')
        string(defaultValue: '1.22.4', description: 'Enter the Go Language Version', name: 'GoLangVersion')
        choice(description: 'Select the OpenShift Release', choices: ['4.22','4.21','4.20','4.19','4.18','4.17','4.16','4.15','4.14','4.13','4.12'], name: 'Release')
        choice(description: 'Select the RedHat Release Version', choices: ['9.7','9.6','8.10'], name: 'RedHatRelease')
        choice(description: 'Select the Configuration', choices: ['min','max','odf'], name: 'Config')
        booleanParam(defaultValue: false, name: 'RunInfoE2e', description: 'Select if you want to run INFO e2e tests. E2e runs after cluster Deployed')
        booleanParam(defaultValue: false, name: 'RunCroE2e', description: 'Select if you want to run CRO e2e tests. E2e runs after cluster Deployed')
        booleanParam(defaultValue: false, name: 'RunMetallbE2e', description: 'Select if you want to run Metallb e2e tests. E2e runs after cluster Deployed')
        booleanParam(defaultValue: false, name: 'RunCoE2e', description: 'Select if you want to run Compliance operator e2e tests. E2e runs after cluster Deployed')
        booleanParam(defaultValue: false, name: 'RunFioE2e', description: 'Select if you want to run Fio operator e2e tests. E2e runs after cluster Deployed')
        booleanParam(defaultValue: false, name: 'InstallLSO', description: 'Install Local Storage Operator')
        string(defaultValue: '', description: 'Enter index image for installing INFO', name: 'IndexImageINFO')
        string(defaultValue: '', description: 'Enter index image for installing LSO', name: 'IndexImageLSO')
        booleanParam(defaultValue: false, name: 'InstallCOO', description: 'Install Cluster Observability Operator')
        string(defaultValue: '', description: 'Enter Catalog Source image for installing COO', name: 'CatalogImageCOO')
        string(defaultValue: '', description: 'Enter index image if you want to run the CO e2e', name: 'IndexImageCo')
        string(defaultValue: '', description: 'Enter index image if you want to run the FIO e2e', name: 'IndexImagefio')
        string(defaultValue: '', description: 'Enter index image if you want to run the Metallb e2e', name: 'IndexImageMetallb')
    } 
    environment {
   
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_USER = credentials('PUBLIC_GITHUB_USER') 
        GITHUB_TOKEN = credentials('PUBLIC_GITHUB_TOKEN')
        OS_USERNAME = credentials('OS_USERNAME')
        OS_PASSWORD = credentials('OS_PASSWORD')
        ARTIFACTORY_USER = credentials('ARTIFACTORY_USER')
        ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')
        REDHAT_USERNAME = credentials('REDHAT_USERNAME')
        REDHAT_PASSWORD = credentials('REDHAT_PASSWORD')
        PULL_SECRET = credentials('PULL_SECRET')

        //Env constants
        HARDWARE_CHOSE = "P9"
        TERRAFORM_VER = "1.9.2"
        TARGET = "deploy-openshift4-powervc"
        TEMPLATE_FILE = ".${TARGET}.tfvars.template"
        POWERVS = false
        SCRIPT_DEPLOYMENT = false
        WAIT_FOR_DEBUG = "1"

        //Branch
        OPENSHIFT_POWERVC_GIT_TF_DEPLOY_BRANCH = "main"//The download branch

        //E2e specific variables
        GOLANG_VERSION = "${params.GoLangVersion}"
        GOLANG_TARBALL = "https://go.dev/dl/go${GOLANG_VERSION}.linux-ppc64le.tar.gz"
        //ClusterResourceOverride operator E2e
        ENABLE_CRO_E2E_TEST = "${params.RunCroE2e}"
        //IngressNodeFirewall operator E2e
        ENABLE_INFO_E2E_TEST = "${params.RunInfoE2e}"
        INFO_CATALOGSOURCE_IMAGE = "${params.IndexImageINFO}" 
        //Metallb operator E2e
        ENABLE_METALLB_E2E_TEST = "${params.RunMetallbE2e}"
        METALLB_CATALOGSOURCE_IMAGE = "${params.IndexImageMetallb}"
        //Compliance Operator e2e
        ENABLE_CO_E2E_TEST = "${params.RunCoE2e}"
        COMPLIANCE_CATALOGSOURCE_IMAGE = "${params.IndexImageCo}"
        //FIO Operator e2e
        ENABLE_FIO_E2E_TEST = "${params.RunFioE2e}"
        FIO_CATALOGSOURCE_IMAGE = "${params.IndexImagefio}"
        //COO Operator e2e 
        ENABLE_COO_INSTALL = "${params.InstallCOO}"
        COO_CATALOGSOURCE_IMAGE = "${params.CatalogImageCOO}"
        COS_STANDARD_KEY= credentials('COS_STANDARD_KEY')
        COS_STANDARD_SECRET= credentials('COS_STANDARD_SECRET')
        //Ip address for metallb Operators E2E
        L2_ADDRESS1="10.20.182.101"
        L2_ADDRESS2="10.20.182.102"
        BGB_ADDRESS1="10.20.182.103"

        //Parameters
        REDHAT_RELEASE="${params.RedHatRelease}"
        OCP_RELEASE="${params.Release}"
        CONFIG_TYPE="${params.Config}"
        BUILD="${params.Build}"
        TIMEOUT = "${params.KeepFor}"

        // kdump Configuration
        KDUMP_ENABLE="false"
    }
    stages {
        stage('Clone ansible extra') {
            steps {
                cloneRepo("https://github.com/Jeevaann/ocp4-playbooks-extras.git", "ocp4-playbooks-extras", "*/coo")
            }
        }
        stage('Setup Common Environment Variables') {
            steps {
                setupCommonEnvironmentVariables()
                setupClusterConfig("${CONFIG_TYPE}")
                script {
                    env.BASTION_MEMORY = "16"
                    
                    // Added a condition for RHCOS_RELEASE to be set to 4.19 for OCP 4.20/4.21/4.22
                    if (env.OCP_RELEASE == "4.20" || env.OCP_RELEASE == "4.21" || env.OCP_RELEASE == "4.22"){
                        env.RHCOS_RELEASE = "4.19"
                    }
                    else {
                        env.RHCOS_RELEASE = env.OCP_RELEASE
                    }
                }
            }
        }
        stage('pull artifact') {
            steps {
                script {
                    getArtifacts("mirror-openshift-release", "latest-${OCP_RELEASE}-build.txt")
                    getArtifacts("powervm/poll-powervc-images", "cicd-rhcos-${RHCOS_RELEASE}.latest.txt")
                    getArtifacts("powervm/poll-powervc-images", "cicd-rhel-${REDHAT_RELEASE}.latest.txt")
                }
            }
        }
        //Checkout the installer git repo
        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                        gbToMb()
                        pullSecret()
                        env.OPENSHIFT_IMAGE = ""
                        if (env.BUILD?.trim()) {
                            if (!env.BUILD.contains('quay')) {
                                env.OPENSHIFT_IMAGE  = "docker-na.artifactory.swg-devops.com/sys-powercloud-docker-local/ocp-ppc64le/release-ppc64le:${env.BUILD}"
                                sh '''
                                    nerdctl login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_TOKEN} docker-na.artifactory.swg-devops.com/sys-powercloud-docker-local
                                    nerdctl pull ${OPENSHIFT_IMAGE}
                                    if [ $? -ne 0 ]; then
                                        echo "${OPENSHIFT_IMAGE}  not found"
                                        exit 1
                                    fi
                                    nerdctl rmi ${OPENSHIFT_IMAGE}
                                '''
                            }
                            else {
                               env.OPENSHIFT_IMAGE=env.BUILD
                            }
                        }
                        else if ( currentBuild.getBuildCauses('hudson.triggers.TimerTrigger$TimerTriggerCause') ){
                            // When its cron job
                            if (fileExists("deploy/artifactory/latest-${OCP_RELEASE}-build.txt")) {
                                env.OPENSHIFT_IMAGE = readFile "deploy/artifactory/latest-${OCP_RELEASE}-build.txt"
                                env.OPENSHIFT_IMAGE = env.OPENSHIFT_IMAGE.trim()
                            }
                            else {
                                echo "latest-${OCP_RELEASE}-build.txt file does not exist. Please check mirror-openshift-release job"
                                throw err
                            }
                        } else {
                            echo "CURRENT build is empty"
                            throw err
                        }
                        if (fileExists("deploy/artifactory/cicd-rhcos-${RHCOS_RELEASE}.latest.txt")) {
                            env.RHCOS_IMAGE = readFile "deploy/artifactory/cicd-rhcos-${RHCOS_RELEASE}.latest.txt"
                            env.RHCOS_IMAGE_NAME = env.RHCOS_IMAGE.split()[0].trim()
                            env.RHCOS_IMAGE_ID = env.RHCOS_IMAGE.split()[1].trim()
                        }
                        else {
                            echo "cicd-rhcos-${RHCOS_RELEASE}.latest.txt file does not exist. Please check poll-powervc-images job"
                            throw err
                        }
                        if (fileExists("deploy/artifactory/cicd-rhel-${REDHAT_RELEASE}.latest.txt")) {
                            env.BASTION_IMAGE = readFile "deploy/artifactory/cicd-rhel-${REDHAT_RELEASE}.latest.txt"
                            env.BASTION_IMAGE_NAME = env.BASTION_IMAGE.split()[0].trim()
                            env.BASTION_IMAGE_ID = env.BASTION_IMAGE.split()[1].trim()
                        }
                        else {
                            echo "cicd-rhel-${REDHAT_RELEASE}.latest.txt file does not exist. Please check poll-powervc-images job"
                            throw err
                        }
                        env.OCP_RELEASE_TAG = env.OPENSHIFT_IMAGE.split(":")[1].trim()
                        env.BUILD = env.OCP_RELEASE_TAG
                        currentBuild.description = "OCP Build: ${OCP_RELEASE_TAG}"
                        createTemplate(env.OS_AUTH_URL, env.MASTER_VCPUS , "${MASTER_MEMORY_MB}", env.MASTER_PROCESSORS, env.MASTER_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.WORKER_VCPUS , "${WORKER_MEMORY_MB}", env.WORKER_PROCESSORS, env.WORKER_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.BASTION_VCPUS , "${BASTION_MEMORY_MB}", env.BASTION_PROCESSORS, env.BASTION_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.BOOTSTRAP_VCPUS , "${BOOTSTRAP_MEMORY_MB}", env.BOOTSTRAP_PROCESSORS, env.BOOTSTRAP_TEMPLATE)
                    }
                    catch (err)
                    {
                        echo 'Error ! Template preparation failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Initialize Environment') {
            steps {
                initializeEnvironment()
            }
        }
        stage('Setup Terraform Plugin') {
            steps {
                setupTerraformPlugin()
            }
        }
        stage('Deploy OCP Cluster') {
            steps {
                deployCluster()
            }
        }
        stage('Run crontab script for capturing outputs of multiple commands') {
            steps {
                crontabCommandCaptureScript()
            }
        }
        stage('Setup Kubectl') {
            steps {
                setupKubeconfigOcp4()
            }
        }
        stage('Validate CO status') {
            steps {
                archiveAllArtifacts("deploy/id_rsa")
                validateCoStatus()
            }
        }
        stage('Run E2e Tests') {
            parallel{
                stage('CRO'){
                    when { expression { return env.ENABLE_CRO_E2E_TEST == "true"; } }
                    steps{
                        script {
                            ansiColor('xterm') {
                            echo ""
                            }
                            try {
                                sh '''
                                    cd ${WORKSPACE} && chmod +x ./scripts/operator/cro_o.sh && ./scripts/operator/cro_o.sh
                                '''
                            }
                            catch(err) {
                                echo 'Running CROO script failed!'
                                failedStages.add(env.STAGE_NAME)
                                throw err
                            }
                        }
                    }
                }
                stage('Metallb'){
                    when { expression { return env.ENABLE_METALLB_E2E_TEST == "true"; } }
                    steps{
                        script{
                            ansiColor('xterm') {
                            echo ""
                            }
                            try {
                                sh '''
                                    cd ${WORKSPACE} && chmod +x ./scripts/operator/metallbOP.sh && ./scripts/operator/metallbOP.sh
                                '''
                            }
                            catch(err) {
                                echo 'Running Metallb script failed!'
                                failedStages.add(env.STAGE_NAME)
                                throw err
                            }
                        }
                    }
                }
                stage('Compliance operator tests'){
                    when { expression { return env.ENABLE_CO_E2E_TEST == "true"; } }
                    steps{
                        script{
                            ansiColor('xterm') {
                            echo ""
                            }
                            try {
                                sh '''
                                    cd ${WORKSPACE} && chmod +x ./scripts/operator/compliance_operator.sh && ./scripts/operator/compliance_operator.sh
                                '''
                            }
                            catch(err) {
                                echo 'Running Compliance_operator script failed!'
                                failedStages.add(env.STAGE_NAME)
                                throw err
                            }
                        }
                    }
                }
                stage('FIO operator tests'){
                    when { expression { return env.ENABLE_FIO_E2E_TEST == "true"; } }
                    steps{
                        script{
                            ansiColor('xterm') {
                            echo ""
                            }
                            try {
                                sh '''
                                    cd ${WORKSPACE} && chmod +x ./scripts/operator/fio_operator.sh && ./scripts/operator/fio_operator.sh
                                '''
                            }
                            catch(err) {
                                echo 'Running FIO_operator script failed!'
                                failedStages.add(env.STAGE_NAME)
                                throw err
                            }
                        }
                    }
                }  
                
                stage('Install COO') {
                    when { expression { return env.ENABLE_COO_INSTALL == "true"; } }
                    steps {
                        script {
                            ansiColor('xterm') {
                            echo ""
                            }
                            try {
                                sh '''
                                    cd ${WORKSPACE} && chmod +x ./scripts/operator/coo_operator.sh && ./scripts/operator/coo_operator.sh
                                '''
                            }
                            catch(err) {
                                echo 'COO operator installation failed!'
                                failedStages.add(env.STAGE_NAME)
                                throw err
                            }
                        }
                    }
                }
		stage('IngressNodeFirewall operator tests'){
                    when { expression { return env.ENABLE_INFO_E2E_TEST == "true"; } }
                    steps{
                        script{
                            ansiColor('xterm') {
                            echo ""
                            }
                            try {
                                sh '''
                                    cd ${WORKSPACE} && chmod +x ./scripts/operator/ingressnfw_opeator.sh && ./scripts/operator/ingressnfw_opeator.sh
                                '''
                            }
                            catch(err) {
                                echo 'Running FIO_operator script failed!'
                                failedStages.add(env.STAGE_NAME)
                                throw err
                            }
                        }
                    }
                }
            }
        }
        stage('Waiting to timeout') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        TIMEOUT_MIN = TIMEOUT.toInteger()
                        if ( TIMEOUT_MIN != 0 )
                        {
                            TIMEOUT_SEC=TIMEOUT_MIN*60
                        }
                        echo "HOLDING THE CLUSTER TEAR DOWN FOR ${TIMEOUT_MIN} MINUTES"
                        sleep TIMEOUT_SEC
                        }
                    catch (err) {
                        echo 'Error ! Timeout stage failed!'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("deploy/croo_e2e_output_*.txt", "deploy/e2e-metallb-repo-logs.txt", "deploy/e2e-metallb-private-logs.txt", "deploy/e2e-output.txt", "deploy/e2e-re-run-output-*.txt", "deploy/fio-e2e-*.txt", "deploy/vars.tfvars")
            cleanupOcp4Cluster()
            checkInfraError()
            script{
                if ( FAILED_STAGE != "" || !failedStages.isEmpty()  ) {
                    FAILED_STAGE="${FAILED_STAGE}${failedStages.join(', ')}"
                    env.MESSAGE = "OCP4 Build: `${BUILD}`, RHCOS: `${env.RHCOS_IMAGE_NAME}`, Failed Stage: `${FAILED_STAGE}`"
                }
            }
            //notifyBySlack(currentBuild.result, env.MESSAGE)
            cleanWs()
        }
    }
}
